steps:
  - id: "Building image from Dockerfile.prod"
    name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-go:$SHORT_SHA', '-f', 'Dockerfile.prod', '.']

  - id: "Pushing image"
    name: 'docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app-go:$SHORT_SHA']

  - id: "Adjusting deployment file - k8s"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-go:$SHORT_SHA#g' k8s/deployment.yaml > k8s/deployment-new.yaml;
        cat k8s/deployment-new.yaml;

  - id: "Deploying k8s"
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/deployment-new.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-laravel'


tags: ['cloud-builders-community']