apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go
spec:
  selector:
    matchLabels:
      app: app-go
  template:
    metadata:
      labels:
        app: app-go
    spec:
      containers:
      - name: app-go
        image: img-app-deployment
        ports:
        - containerPort: 8123